/*
 *      Definition of the header constant for the header file content. 
 */

static char *testrun_header = 
"/***\n"
"        ------------------------------------------------------------------------\n"
"\n"
"        Copyright 2017 Markus Toepfer\n"
"\n"
"        Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"        you may not use this file except in compliance with the License.\n"
"        You may obtain a copy of the License at\n"
"\n"
"                http://www.apache.org/licenses/LICENSE-2.0\n"
"\n"
"        Unless required by applicable law or agreed to in writing, software\n"
"        distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"        See the License for the specific language governing permissions and\n"
"        limitations under the License.\n"
"\n"
"        This file is part of the testrun project. http://testrun.info\n"
"\n"
"        ------------------------------------------------------------------------\n"
"*//**\n"
"\n"
"        @file           testrun.h\n"
"        @author         Markus Toepfer\n"
"        @date           2017-11-24\n"
"\n"
"        @brief          Simple serial test execution framework.\n"
"\n"
"        NOTE            This framework uses an alternative to assert based\n"
"                        testing, which is compatible with parallel\n"
"                        test execution of @see testrun2.h. So this header is\n"
"                        replacable with testrun2.h for parallel test setup,\n"
"                        without replacing any written testcase.\n"
"\n"
"                        (Assert.h is not included, to force to write testrun2.h\n"
"                        compatible tests by default)\n"
"\n"
"        ------------------------------------------------------------------------\n"
"*/\n"
"\n"
"#ifndef testrun_h\n"
"#define testrun_h\n"
"\n"
"#include <unistd.h>     /* C89/C90 */\n"
"#include <stdlib.h>     /* C89/C90 */\n"
"#include <stdio.h>      /* C89/C90 */\n"
"#include <string.h>     /* C89/C90 */\n"
"#include <errno.h>      /* C89/C90 */\n"
"#include <time.h>       /* C89/C90 */\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"\n"
"/**\n"
"        String error initialization of no error.\n"
"*/\n"
"#define testrun_errno() \\\n"
"        (errno == 0 ? \"NONE\" :  strerror(errno))\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"\n"
"/**\n"
"        Log a failure. Failure: Inability to perform a function as expected.\n"
"*/\n"
"#define testrun_log_failure(msg, ...) \\\n"
"        fprintf(stderr, \"\\t[FAIL]\\t%s line:%d errno:%s message: \" msg \"\\n\",\\\n"
"        __FUNCTION__, __LINE__, testrun_errno(), ##__VA_ARGS__)\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"\n"
"/**\n"
"        Log an error. Error: Difference between expected and actual result.\n"
"*/\n"
"#define testrun_log_error(msg, ...) \\\n"
"        fprintf(stderr, \"\\t[ERROR]\\t%s line:%d errno:%s message: \" msg \"\\n\",\\\n"
"        __FUNCTION__, __LINE__, testrun_errno(), ##__VA_ARGS__)\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"\n"
"#define testrun_log_success(msg, ...) \\\n"
"        fprintf(stdout, \"\\t[OK] \\t%s \" msg \"\\n\", __FUNCTION__, ##__VA_ARGS__)\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"\n"
"#define testrun_log(msg, ...) \\\n"
"        fprintf(stdout, \"\\t\" msg \"\\n\", ##__VA_ARGS__)\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"\n"
"#define testrun_log_function_info(msg, ...) \\\n"
"        fprintf(stdout, \"\\t[INFO] \\t%s line:%d message: \" msg \"\\n\", \\\n"
"                __FUNCTION__, __LINE__, ##__VA_ARGS__)\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"\n"
"#define testrun_log_clock(start, end) \\\n"
"        fprintf(stdout, \"\\tClock ticks function: ( %s ) | %f s | %.0f ms \\n\", \\\n"
"        __func__, \\\n"
"        ((double)(end - start)) / CLOCKS_PER_SEC, \\\n"
"        (((double)(end - start)) / CLOCKS_PER_SEC ) * 1000)\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"\n"
"#define testrun_init()  \\\n"
"        int result = 0; \\\n"
"        int testrun_counter = 0;\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"\n"
"/**\n"
"        Run a single atomar test. Return the surrounding block on error.\n"
"        This function will leave the context block running on error. The\n"
"        Mindset is a defused assert. LEAVE THE FUNCTION NOT THE PROGRAM.\n"
"\n"
"        @param test     boolean decision input.\n"
"        @returns        the calling function on error with -1\n"
"*/\n"
"#define testrun_check(test, ... )\\\n"
"        if (!(test)) { testrun_log_error(__VA_ARGS__);  return -1;}\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"\n"
"/**\n"
"        Alias to @see testrun_check.\n"
"*/\n"
"#define testrun(test, ...)\\\n"
"        testrun_check(test, __VA_ARGS__ )\n"
"\n"
"/*----------------------------------------------------------------------------*/\n"
"\n"
"/*--------------- For EXAMPLE code check http://testrun.info -----------------*/\n"
"/**\n"
"        Run a single test (execute a function pointer. Runs a test function.\n"
"        On non negative return value of the function run, a testrun_counter\n"
"        is increased, on negative result, the negative result will be returned.\n"
"\n"
"        @param test     function pointer of the test to run\n"
"        @NOTE           The surrounding block is left on negative result of the\n"
"                        function pointer execution.\n"
"*/\n"
"#define testrun_test(test)\\\n"
"        result = test(); testrun_counter++; if (result < 0) return result;\n"
"\n"
"/**\n"
"        Runs a function pointer, which SHALL contain the test function pointers\n"
"        to run. The function pointer is wrapped in a main procedure, which and\n"
"        allows indepentent testruns of the input testcluster over external\n"
"        execution.\n"
"\n"
"        A clock will be started, as soon as the main is executed and the the\n"
"        time is stopped again, at the end of the execution. The difference\n"
"        will be printed and is the runtime of the whole input testcluster.\n"
"\n"
"        A run will fail, as soon as one of the tests in the testcluster fails.\n"
"        (Fail on first) or will run all functions dependent on the testsetup.\n"
"\n"
"        @param testcluster      function pointer to be executed.\n"
"*/\n"
"#define testrun_run(testcluster) int main(int argc, char *argv[]) {\\\n"
"        argc = argc;\\\n"
"        clock_t start1_t, end1_t; \\\n"
"        start1_t = clock(); \\\n"
"        testrun_log(\"\\ntestrun\\t%s\", argv[0]);\\\n"
"        int64_t result = testcluster();\\\n"
"        if (result > 0) \\\n"
"                testrun_log(\"ALL TESTS RUN (%jd tests)\", result);\\\n"
"        end1_t = clock(); \\\n"
"        testrun_log_clock(start1_t, end1_t); \\\n"
"        testrun_log(\"\");\\\n"
"        result >=0 ? exit(EXIT_SUCCESS) : exit(EXIT_FAILURE); \\\n"
"}\n"
"\n"
"/**     -----------------------------------------------------------------------\n"
"\n"
"        @example        testrun_base_example.c\n"
"        @author         Markus Toepfer\n"
"        @date           2017-11-24\n"
"\n"
"        @brief          Example test file using testrun.h\n"
"\n"
"        This example shows the test style for testing with testrun.h and is\n"
"        build around the testrun_test() macro, which increases a counter which\n"
"        MUST be initialized in a testcluster function.\n"
"\n"
"        //---------------------------------------------------------------------\n"
"\n"
"        @code\n"
"        #include \"../tools/testrun.h\"\n"
"\n"
"        int example_function() {\n"
"                return 1;\n"
"        }\n"
"\n"
"        //---------------------------------------------------------------------\n"
"\n"
"        int test_function1() {\n"
"\n"
"                // use of testrun_check() for evaluation\n"
"                testrun_check(1 == 1);\n"
"                testrun_check(1 == 1, \"some additional information\");\n"
"\n"
"                // use of testrun() for evaluation\n"
"                testrun(1 == 1);\n"
"                testrun(1 == 1, \"some additional information\");\n"
"\n"
"                // use of manual evaluation and logging\n"
"                if (1 != example_function()){\n"
"                        testrun_log_error(\"some additional information.\");\n"
"                        return -1;\n"
"                }\n"
"\n"
"                // will not be reached in case of error\n"
"                return testrun_log_success();\n"
"        }\n"
"\n"
"        //---------------------------------------------------------------------\n"
"\n"
"        int test_function2() {\n"
"\n"
"                testrun_check(1 == 1);\n"
"                return testrun_log_success();\n"
"        }\n"
"\n"
"        //---------------------------------------------------------------------\n"
"\n"
"        int test_function3() {\n"
"\n"
"                testrun_check(1 == 1);\n"
"                return testrun_log_success();\n"
"        }\n"
"\n"
"        //---------------------------------------------------------------------\n"
"\n"
"        int testcase_cluster() {\n"
"\n"
"                testrun_init();\n"
"\n"
"                testrun_test(test_function1);\n"
"                testrun_test(test_function2);\n"
"                testrun_test(test_function3);\n"
"\n"
"                return testrun_counter;\n"
"\n"
"        }\n"
"\n"
"        testrun_run(testcase_cluster);\n"
"        @endcode\n"
"\n"
"*/\n"
"\n"
"#endif /* testrun_h */\n";
